Jungle-5pointers/5_pointers

backend/package-lock.json
backend/package.json
frontend/src/pages/NoCodeEditor.jsx
frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
frontend/src/pages/NoCodeEditor/Inspector.jsx
frontend/src/pages/components/definitions/button.json
frontend/src/pages/components/definitions/index.js
frontend/src/pages/components/definitions/link.json
frontend/src/pages/components/definitions/text.json

- 컴포넌트 디렉토리 변경 및 기초 틀
- close #1 
- 변경 1: 컴포넌트 디렉토리 구조 변경 및 기초 틀 만들기
- 변경 2: 링크 컴포넌트 추가
- json 파일로 컴포넌트 추가하면 됩니다
```
{
"type": "text",           // 컴포넌트 타입
"label": "텍스트",        // UI에 표시될 이름
"edit": {                 // edit 모드 - 속성 편집기 정의
"text": { "label": "내용", "type": "text" },
"fontSize": { "label": "글자 크기", "type": "number" },
"color": { "label": "글자 색상", "type": "color" }
},
"defaultProps": {         // 기본 속성값
"text": "내용을 입력하세요",
"fontSize": 20,
"color": "#222"
}
}
```

컴포넌트 기초 틀 구성

---

backend/src/main.ts
frontend/src/pages/NoCodeEditor/Inspector.jsx
frontend/src/pages/NoCodeEditor/PropertyEditors/ColorEditor.jsx
frontend/src/pages/NoCodeEditor/PropertyEditors/NumberEditor.jsx
frontend/src/pages/NoCodeEditor/PropertyEditors/TextEditor.jsx
frontend/src/pages/NoCodeEditor/PropertyEditors/index.js

컴포넌트 에디터 속성별 분리
- close #14
- 변경 1: NoCodeEditor/ PropertyEditors 생성

컴포넌트 에디터 속성별 분리

---

frontend/src/pages/NoCodeEditor.jsx

DB ERD 작성한대로 entity 테이블 추가했습니다.
- close # 7
- 변경 1: 추가 테이블(page_members, pages, submissions)

DB entity 테이블 추가(page_members, pages, submissions)

---

.gitignore
frontend/src/pages/NoCodeEditor.jsx
frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
mysql-mcp-server/package.json
mysql-mcp-server/src/index.ts
mysql-mcp-server/tsconfig.json

Feat: 배포버튼 추가

---

.gitignore
backend/src/auth/auth.service.ts
backend/src/auth/jwt.strategy.ts
backend/src/users/entities/pages.entity.ts
backend/src/users/users.controller.ts
backend/src/users/users.module.ts
backend/src/users/users.service.ts
frontend/src/pages/DashboardPage.jsx
frontend/src/pages/LoginPage.jsx
frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
package-lock.json
package.json
subdomain-server.js

subdomain DB , create new pages -> database 에 id ,저장

---

frontend/package-lock.json
frontend/src/pages/NoCodeEditor.jsx
frontend/src/pages/NoCodeEditor/ComponentEditors/MapInfoEditor.jsx
frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
frontend/src/pages/NoCodeEditor/ComponentRenderers/MapInfoRenderer.jsx
frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
frontend/src/pages/NoCodeEditor/Inspector.jsx
frontend/src/pages/components/definitions/index.js
frontend/src/pages/components/definitions/map_info.json

장소안내 컴포넌트 추가 및 충돌 해결
- close #48 
- 변경 1: 장소안내 컴포넌트 추가
- 변경 2: 충돌 해결

fix: component_mapinfo 브랜치 최종 충돌 해결 및 MapInfo 관련 파일 추가

---

frontend/src/pages/NoCodeEditor.jsx
frontend/src/pages/NoCodeEditor/ComponentEditors/GridGalleryEditor.jsx
frontend/src/pages/NoCodeEditor/ComponentEditors/SlideGalleryEditor.jsx
frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
frontend/src/pages/NoCodeEditor/ComponentRenderers/GridGalleryRenderer.jsx
frontend/src/pages/NoCodeEditor/ComponentRenderers/SlideGalleryRenderer.jsx
frontend/src/pages/NoCodeEditor/ComponentRenderers/SlideGalleryRenderer.jsx.backup
frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
frontend/src/pages/NoCodeEditor/Inspector.jsx
frontend/src/pages/NoCodeEditor/PropertyEditors/BooleanEditor.jsx
frontend/src/pages/NoCodeEditor/PropertyEditors/ImageListEditor.jsx
frontend/src/pages/NoCodeEditor/PropertyEditors/index.js
frontend/src/pages/components/definitions/grid-gallery.json
frontend/src/pages/components/definitions/index.js
frontend/src/pages/components/definitions/slide-gallery.json
mysql-mcp-server/package.json
package-lock.json
package.json

갤러리 컴포넌트 추가
- close #45 
- 변경 1: 
체크박스 | 체크박스 형태의 boolean 값 편집 | BooleanEditor.jsx 
이미지 리스트 | 다중 이미지 목록 관리 | ImageListEditor.jsx |   | 다중 이미지 업로드이미지 순서 변경개별 이미지 삭제이미지별 캡션 추가이미지 미리보기
- 변경 2:

갤러리 컴포넌트 추가

---

frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
frontend/src/pages/NoCodeEditor/Inspector.jsx
frontend/src/pages/components/definitions/index.js

Fix: 이제 진짜 됨

---

frontend/src/pages/NoCodeEditor.jsx
frontend/src/pages/NoCodeEditor/CanvasArea.jsx
frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
frontend/src/pages/NoCodeEditor/Inspector.jsx
frontend/src/pages/components/definitions/index.js

그리드와 컴포넌트 딱딱 맞음, 확대해도 위치 동일
- close #40 
- 변경 1: NoCodeEditor.jsx, Inspector.jsx, CanvasArea.jsx, ComponentLibrary.jsx

feat : 캔버스 제작 중

---

frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
frontend/src/pages/NoCodeEditor/Inspector.jsx

오늘의 최고 완벽본

---

frontend/src/pages/NoCodeEditor/Inspector.jsx

메인 깨지는 현상 고침

---

backend/src/users/users.controller.ts
frontend/src/pages/NoCodeEditor.jsx
frontend/src/pages/NoCodeEditor/CanvasArea.jsx
frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
frontend/src/pages/NoCodeEditor/ViewportController.jsx

Canvars 충돌방지, 확장기, 스냅라인
- close #62 
- 변경 1: canvasArea

Canvars 충돌방지, 확장기, 스냅라인

---

frontend/src/components/collaboration/LiveCursors.jsx
frontend/src/hooks/useLiveCursors.js
frontend/src/pages/NoCodeEditor.jsx
frontend/src/pages/NoCodeEditor/CanvasArea.jsx
package-lock.json
package.json
yjs-server.js

yjs 컴포넌트 선택시 커서, 편집 중 테두리 -> 더 작업해야함
- close #71

editor very upgrade

---

frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
frontend/src/pages/NoCodeEditor/utils/editorUtils.js

WeddingInvite 관련 기능 구현 및 오류 수정
- close #48 
- 변경 1: CanvasComponent.jsx에서 import 및 case 추가
- 변경 2: editorUtils.js에 "컴포넌트 타입별 기본 크기와 최소 크기 정의"에 weddingInvite 추가
WeddingInviteRenderer.jsx
CanvasComponent,jsx
editorUtils.js
만 수정함
-없음

WeddingInvite 관련 기능 구현 및 오류 수정

---

frontend/src/hooks/useCollaboration.js
frontend/src/pages/NoCodeEditor.jsx

컴포넌트 렌더링 수정
- 변경 1:컴포넌트 렌더링 수정

컴포넌트 렌더링 수정

---

frontend/src/pages/NoCodeEditor/ComponentEditor.jsx

ComponentEditor.jsx의 import 수정
- close #84  
- 변경: import MusicPlayerEditor from './ComponentEditors/MusicEditor'; 에서 MusicPlayerEditor를 MusicEditor로 수정

ComponentEditor.jsx의 import 수정

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/NoCodeEditor/Inspector.jsx

inspector.jsx에 빠진 부분 다시 수정
- close #84 
- 변경: switch-case, getCommponentIcon,getComponentLabel에 빠진 부분 수정

inspector.jsx에서 music관련 빠진 부분 수정

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/CalendarRenderer.jsx

Calendar 컴포넌트 수정 

---

package-lock.json
package.json
yjs-server.js

동시성 yjs 오류 수정
- close #106 
- 변경 1:yjs.server.js

동시성 yjs 오류 수정

---

backend/package-lock.json
backend/src/auth/auth.service.ts
backend/src/generator/generator.service.ts
backend/src/main.ts
backend/src/templates/templates.service.ts
backend/src/users/users.controller.ts
backend/src/users/users.service.ts
my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
my-web-builder/apps/frontend/src/hooks/useAutoSave.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/ButtonRenderer.jsx
yjs-server.js

자동 저장 기능 통합 및 디버깅
- close #108 
- 변경 1:자동 저장 기능 통합
- 변경 2:
- 개선된 렌더링 순서
페이지 접근 → 즉시 데이터 로드
즉시 렌더링 → YJS 대기 없음
YJS 연결 → 백그라운드에서 협업 준비
자동저장 → useAutoSave로 2초 마다
렌더링 빠르게 개선, 중복 기능 삭제 및 통합

자동 저장 기능 통합 및 디버깅

---

.github/workflows/5pointers-backend-deploy.yml
.github/workflows/5pointers-deploy-all.yml
.github/workflows/5pointers-editor-deploy.yml
.github/workflows/5pointers-subdomain-deploy.yml
.github/workflows/5pointers-websocket-deploy.yml
setup-5pointers-runner.sh

- Add backend deployment workflow (NestJS)
- Add frontend editor deployment workflow (React/Vite)
- Add subdomain renderer deployment workflow (Next.js)
- Add WebSocket server deployment workflow
- Add unified deployment workflow for all services
- Add GitHub Actions runner setup script for EC2 instances
- close # 
- 변경 1:
- 변경 2:

q developer의 실력 뽐내기 (cicd 자동화)

---

.github/workflows/5pointers-backend-deploy.yml
.github/workflows/5pointers-editor-deploy.yml
.github/workflows/5pointers-subdomain-deploy.yml

- Add --no-frozen-lockfile flag to pnpm install commands
- Add fallback build strategies for missing build scripts
- Add fallback server creation for missing main files
- Improve error handling and deployment robustness
- Fix pnpm lockfile synchronization issues
- close # 
- 변경 1:
- 변경 2:

🔧 Fix CI/CD workflows

---

.github/workflows/5pointers-backend-deploy.yml
.github/workflows/5pointers-editor-deploy.yml
backend/test-deployment.txt
my-web-builder/apps/editor/test-deployment.txt

- Add test files to backend/ and frontend/editor/
- This should trigger both backend and frontend deployment workflows
- Testing self-hosted runners functionality
- close # 
- 변경 1:
- 변경 2:

🧪 Trigger CI/CD workflows

---

my-web-builder/apps/frontend/src/pages/MainPage.jsx

AWS git action test

---

.github/workflows/5pointers-frontend-deploy.yml

Add frontend workflow

---

.github/workflows/deploy-backend.yml
.github/workflows/deploy-frontend.yml
my-web-builder/apps/frontend/src/config.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor/Inspector.jsx

google oauth git action 설정

---

my-web-builder/apps/frontend/src/config.js

api api 중복 테스트
- close # 
- 변경 1:
- 변경 2:

api api 중복 테스트

---

.github/workflows/deploy-backend.yml
.github/workflows/deploy-frontend.yml

카카오 구글 로그인 테스트

---

.github/workflows/deploy-backend.yml
backend/src/auth/auth.service.ts
my-web-builder/apps/frontend/src/App.tsx
my-web-builder/apps/frontend/src/hooks/useCollaboration.js
my-web-builder/apps/frontend/src/pages/AppEditor.jsx
my-web-builder/apps/frontend/src/pages/LoginPage.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary.jsx
my-web-builder/apps/frontend/src/pages/SocialCallbackPage.jsx

소셜 로그인 오류 절대 안남 완벽 해결

---

my-web-builder/apps/frontend/src/pages/InvitationHandler.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx

초대 오류 고침 제발 고장나지말아라
- close # 
- 변경 1:
- 변경 2:

초대 오류 고침 제발 고장나지말아라

---

.github/workflows/deploy-backend.yml
.github/workflows/subdomain-server.yml
DEPLOYMENT_UPDATES.md
GITHUB_SECRETS_SETUP.md
deployment-script.sh
fix-subdomain-deployment.sh
get-instance-id.sh
setup-ssm-agent.sh
subdomain-server.js

이제 진짜 됨 메이비

---

.github/workflows/subdomain-server.yml
create-new-subdomain-ec2.sh
subdomain-server.js

Subdomain fixing

---

backend/src/users/users.controller.ts
backend/src/users/users.service.ts
my-web-builder/apps/frontend/src/hooks/useComponentActions.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/PageEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/PageThumbnail.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/index.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/PageRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor/Inspector.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/PageNavigation.jsx
my-web-builder/apps/frontend/src/pages/components/definitions/index.js
my-web-builder/apps/frontend/src/pages/components/definitions/page.json

페이지 컴포넌트, 네비게이션 일부 완성
- close # 
- 변경 1: 페이지 컴포넌트 관련 파일
- 변경 2:

Add page component

---

my-web-builder/apps/frontend/.env.staging

VITE_YJS_WEBSOCKET_URL 변경
- close # 
- 변경 1:
- 변경 2:

VITE_YJS_WEBSOCKET_URL 변경

---

my-web-builder/apps/frontend/src/config.js

yjs vite websocket url
- close # 
- 변경 1:
- 변경 2:

yjs vite websocket url

---

backend/src/app.module.ts

- app.module.ts에서 중복된 Templates 엔티티 import 제거
- GitHub Actions 빌드 오류 해결
import 중복 오류 제거
- close # 
- 변경 1:
- 변경 2:

fix: 중복된 Templates import 제거

---

.github/workflows/deploy-frontend.yml
my-web-builder/apps/frontend/src/config.js

236 yjs deploy

---

.github/workflows/deploy-frontend.yml
my-web-builder/apps/frontend/src/config.js

🚨 문제:
- HTTPS 페이지에서 WS 연결 시 브라우저 보안 정책 차단
- SecurityError: An insecure WebSocket connection may not be initiated from a page loaded over HTTPS
✅ 해결:
- WSS(WebSocket Secure) 사용: wss://3.35.50.227:1235
- 자체 서명 인증서 사용 (개선된 SAN 설정)
- 브라우저에서 인증서 수동 승인 필요
⚠️ 사용자 액션 필요:
1. https://3.35.50.227:1235 직접 접속
2. 보안 경고에서 '고급' → '안전하지 않음으로 이동' 클릭
3. 인증서 승인 후 페이지 새로고침
- close # 
- 변경 1:
- 변경 2:

🔒 WSS 사용으로 Mixed Content 오류 해결

---

deploy-nextjs-subdomain.sh
manual-deploy-nextjs.sh
my-web-builder/apps/subdomain-nextjs/deploy-nextjs.sh
my-web-builder/apps/subdomain-nextjs/package.json

ec2 인스턴스 실행하기 

---

.github/workflows/deploy-backend.yml.backup
.github/workflows/deploy-frontend.yml

Fix: session_token 제거
- close # 
- 변경 1:
- 변경 2:

Fix: session_token 제거

---

my-web-builder/apps/frontend/src/hooks/useComponentActions.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx

- Remove drag position logs from CanvasComponent
- Remove component rendering logs from CanvasArea
- Remove Y.js update and property change logs from useComponentActions
- Remove copy/paste operation logs from NoCodeEditor
- Remove component selection logs from CanvasArea
This improves performance and reduces console noise during development.
- close # 
- 변경 1:
- 변경 2:

🧹 Remove debug console logs

---

backend/src/s3/s3.service.ts

찐막 s3업로드 수정

---

backend/src/generator/generator.service.ts

페이지의 주인은 같은 서브도메인 사용 가능

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/maps/maps.controller.ts
backend/src/maps/maps.module.ts
my-web-builder/apps/subdomain-nextjs/components/renderers/MapView.jsx
my-web-builder/apps/subdomain-nextjs/next-env.d.ts
package-lock.json
package.json

지도 에디터, 캔버스, 배포했을 때 동일하게 적용
- close # 
- 변경 1:
- 변경 2:

지도 에디터, 캔버스, 배포했을 때 동일하게 적용

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx

- 편집 기준 모바일일 때 캔버스 중앙에 위치
- close # 
- 변경 1:
- 변경 2:

편집 기준 모바일일 때 캔버스 중앙에 위치

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx

컴포넌트 선택 클릭아니고, 컨트롤 클릭해야지 다중선택 이영준 빡침 해결완료
- close # 
- 변경 1:
- 변경 2:

컴포넌트 선택 클릭아니고, 컨트롤 클릭해야지 다중선택 이영준 빡침 해결완료

---

backend/src/migrations/add-editing-mode-to-templates.sql
backend/src/templates/templates.controller.ts
backend/src/templates/templates.service.ts
backend/src/users/entities/templates.entity.ts
my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
my-web-builder/apps/frontend/src/hooks/useComponentActions.js
my-web-builder/apps/frontend/src/hooks/useEditorInteractionManager.js
my-web-builder/apps/frontend/src/hooks/usePageDataManager.js
my-web-builder/apps/frontend/src/pages/Dashboard.jsx
my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx

모바일 캔버스 중간, 뷰포트  모바일, 데스크톱 컬럼 추가
- close # 
- 변경 1:
- 변경 2:

모바일 캔버스 중간, 뷰포트  모바일, 데스크톱 컬럼 추가

---

backend/src/templates/templates.controller.ts
backend/src/templates/templates.service.ts
my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ViewportController.jsx

대시보드 미리보기 모바일, 데스크톱 구분

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx

컨트롤 클릭시 다중선택
- close # 
- 변경 1:
- 변경 2:

컨트롤 클릭시 다중선택

---

backend/src/auth/jwt.strategy.ts
backend/src/main.ts
backend/src/templates/templates.controller.ts

 템플릿 조회 디버깅

---

my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/KakaoTalkShareRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingContentRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js

빈 큐브 시작을 테마 밑으로 옮김
- close # 
- 변경 1:
- 변경 2:

빈 큐브 시작을 테마 밑으로 옮김

---

backend/src/auth/auth.service.ts
backend/src/auth/jwt.strategy.ts
backend/src/main.ts
my-web-builder/apps/subdomain-nextjs/next-env.d.ts

 jwt 건드리다가 로컬에서 로그인안되던거 수정

---

my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
my-web-builder/apps/frontend/src/pages/DashboardPage.jsx

데스크톱 미리보기도 완벽함

---

backend/src/main.ts
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/styles/preview.css
test-packages.js

미리보기 모바일 뷰 추가
- close #298 
- 변경 1: /home/chunbai/5pointers/my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
- 변경 2: /home/chunbai/5pointers/my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx

Add mobile view #298

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/KakaoTalkShareRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx

fix: 터짐 해결

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/ComponentCard.jsx

썸네일 텍스트 정렬
- close #344 
- 변경 1:
- 변경 2:
ComponentCard.jsx 딱 한줄만 수정

썸네일 텍스트 수정

---

backend/src/generator/generator.service.ts
backend/src/invitations/invitations.gateway.ts
backend/src/main.ts
backend/src/users/users.controller.ts
my-web-builder/apps/frontend/src/components/InvitationNotifications.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/PageNavigation.jsx

로컬에서 이미지 업로드 및 잔버그 수정
- close # 
- 변경 1:
- 변경 2:

Fix: 로컬에서 이미지 업로드 및 잔버그

---

.github/workflows/deploy-backend.yml.backup
backend/src/users/users.controller.ts
backend/src/users/users.service.ts
my-web-builder/apps/frontend/src/hooks/usePageMembers.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/InviteModal.jsx
my-web-builder/apps/frontend/src/utils/userUtils.js

페이지 멤버 표시 기능 구현
- close # 
- 변경 1:
- 변경 2:

페이지 멤버 표시 기능 구현

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js

slido 컴포넌트 리사이즈 핸들러에 맞게 크기 조정
- close #349 
- 변경 1:
- 변경 2:
editorUtils에서 크기만 바꿨음

slido 크기 수정

---

my-web-builder/apps/frontend/src/data/musicLibrary.js

음악파일 S3에 업로드함
- close # 
- 변경 1:
- 변경 2:

Feat: 음악파일 S3에 업로드함

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/BankAccountEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/CommentEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/TextComponentEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/TextAreaEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/TextEditor.jsx
my-web-builder/apps/frontend/src/utils/debounce.js

edit 에서 한글 입력 고침

---

.github/workflows/deploy-frontend.yml
README.md
my-web-builder/apps/frontend/.env.staging
my-web-builder/apps/frontend/src/config.js
my-web-builder/apps/subdomain-nextjs/deploy-ec2.sh
restart-yjs-ssl-server.sh
yjs-server.js

 yjs 서버 재가동

---

.github/workflows/deploy-frontend.yml

deploy-frontend
- close # 
- 변경 1:
- 변경 2:

deploy-frontend

---

.github/workflows/deploy-frontend.yml
my-web-builder/apps/frontend/src/config.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx

일단 mixed content HTTP

---

backend/src/generator/generator.controller.ts
backend/src/generator/generator.service.ts
backend/src/users/users.controller.ts
backend/src/users/users.service.ts
my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/AttendEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/components/DeploySection.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/hooks/useDeploy.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/DeployModal.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
my-web-builder/apps/subdomain-nextjs/next-env.d.ts

버튼 비활 에디터모드

---

my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/ButtonRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/DdayRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/GridGalleryRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/ImageRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/KakaoTalkShareRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/LinkCopyRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/LinkRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/MusicRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/PageRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/SlideGalleryRenderer.jsx
my-web-builder/apps/subdomain-nextjs/next-env.d.ts

Gridgallary z-index값 수정 
미리보기하면 다른 컴포넌트들 다 가리게 수정
isEditor남아있는 일부 파일들 없애고 mode로 통일
- close #426

Gridgallary z-index값 수정 

---

.github/workflows/deploy-frontend.yml
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/KakaoTalkShareRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MapView.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/MusicRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/KakaoTalkShareRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/MapView.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/MusicRenderer.jsx
my-web-builder/apps/subdomain-nextjs/next.config.js

카카오톡 공유하기 배포로직에 key값 추가 , music 컴포넌트 변수 선언 수정

카카오톡 공유하기 배포로직에 key값 추가 , music 컴포넌트 변수 선언 수정

---

my-web-builder/apps/subdomain-nextjs/next.config.js
my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx

typescript 오류 해결

---

my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx

build 오류 해결
- close # 
- 변경 1:
- 변경 2:

build 오류 해결

---

.github/workflows/deploy-frontend.yml
my-web-builder/apps/subdomain-nextjs/next.config.js

Next.js 정적 내보내기 설정
- close # 
- 변경 1:
- 변경 2:

Next.js 정적 내보내기 설정

---

backend/src/auth/auth.service.ts

카카오 구글 오류 해결~~
- close # 
- 변경 1:
- 변경 2:

카카오 구글 오류 해결~~

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/BankAccountRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/GridGalleryRenderer.jsx

미리보기 딱맞게 수정 + AttendRenderers 수정

---

my-web-builder/apps/frontend/src/components/collaboration/ChatBubble.jsx
my-web-builder/apps/frontend/src/components/collaboration/ChatInput.jsx
my-web-builder/apps/frontend/src/hooks/useChat.js
my-web-builder/apps/frontend/src/hooks/useCollaboration.js

채팅 중복 id 생성 방지 로직, mac os 채팅보 않는 문제 개선 테스트

채팅 중복 id 생성 방지 로직, mac os 채팅보 않는 문제 개선 테스트

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/SlidoEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/TextComponentEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/WeddingInviteEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/TextEditor.jsx

안내장, Slido 한글 입력 수정
- close #444
- 변경 1:
- 변경 2:

안내장, Slido 한글 입력 수정

---

my-web-builder/apps/frontend/src/components/collaboration/ChatInput.jsx
my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
my-web-builder/apps/frontend/src/hooks/useChat.js
my-web-builder/apps/frontend/src/hooks/useCollaboration.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx

채팅 기능 커서 옆 이름 아래에 보이게

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx

텍스트 컴포넌트 정렬 기능 
- close #456 
- 변경 1:
- 변경 2:

텍스트 컴포넌트 정렬 기능 

---

my-web-builder/apps/frontend/src/pages/DashboardPage.jsx

dashboard header 수정

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/TextComponentEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx

텍스트 기본값 중앙 정렬
- close # 
- 변경 1:
- 변경 2:
꼼꼼한 체크 못했음

텍스트 기본값 중앙 정렬

---

backend/src/users/users.service.ts
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/SlidoEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/CommentRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/SlidoRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
my-web-builder/apps/frontend/src/pages/components/definitions/slido.json
my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/BankAccountRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/CalendarRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/CommentRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/SlideGalleryRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/SlidoRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/WeddingInviteRenderer.jsx
my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx

Slido 컴포넌트 디자인 수정 & 컴포넌트 테두리 배포 후 화면 반영
- close #475
- close #476 
- 변경 1: Slido 컴포넌트 디자인 수정
- 변경 2: 컴포넌트 테두리 배포 후 화면 반영

Slido 컴포넌트 디자인 수정 & 컴포넌트 테두리 배포 후 화면 반영

---

my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
my-web-builder/apps/frontend/src/pages/DraftsPage.jsx

drafts 페이지, deployed 페이지 수정

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx

build error 해결

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx

sorry
- close # 
- 변경 1:
- 변경 2:

useEffect 괄호안닫음

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/DeployModal.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/EditorHeader.jsx

최종 배포 모달 디자인 수정

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx

🎯 사용법:
코멘트 입력: / 키를 누르면 현재 커서 위치에 코멘트 입력창이 열림
컴포넌트 삭제: 컴포넌트를 선택한 후 Delete 또는 Backspace 키로 삭제 가능
🔧 기술적 변경사항:
CanvasArea.jsx: onContextMenu 이벤트 핸들러 제거
NoCodeEditor.jsx: 키보드 이벤트에서 Backspace 키 조건 추가

코멘트달때 마우스 오른쪽 버튼 클릭 없앰. 컴포넌트 삭제 backspace 가능

---

my-web-builder/apps/frontend/src/pages/DeployedPage.jsx

deploy page에서 편집하기 누르면 url에 viewport 파라미터 제거
- close # 
- 변경 1:
- 변경 2:

deploy page에서 편집하기 누르면 url에 viewport 파라미터 제거

---

.github/workflows/deploy-backend.yml
backend/src/auth/auth.service.ts
my-web-builder/apps/frontend/src/pages/LoginPage.jsx
my-web-builder/apps/frontend/src/pages/MainPage.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/DeployModal.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/InviteModal.jsx
my-web-builder/apps/frontend/src/pages/SignupPage.jsx

카카오 소셜 오류 해결 테스트

---

my-web-builder/apps/frontend/src/App.tsx
my-web-builder/apps/frontend/src/components/InvitationNotifications.jsx
my-web-builder/apps/frontend/src/components/Toast.jsx
my-web-builder/apps/frontend/src/components/ToastExample.jsx
my-web-builder/apps/frontend/src/contexts/ToastContext.jsx
my-web-builder/apps/frontend/src/hooks/useComponentActions.js
my-web-builder/apps/frontend/src/hooks/useToast.js
my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/InviteModal.jsx
my-web-builder/apps/frontend/src/pages/SocialCallbackPage.jsx

토스트 알림 고치는 중

---

.github/workflows/deploy-frontend.yml
backend/src/auth/auth.service.ts
backend/src/main.ts

deploy frontend yml 수정

---

backend/src/users/users.service.ts
my-web-builder/apps/frontend/src/components/NotificationToggle.jsx
my-web-builder/apps/frontend/src/hooks/useEditorInteractionManager.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/KakaoTalkShareEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary.backup.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/AttendRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/BankAccountRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/ButtonRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/CommentRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/LinkRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/SlidoRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/ImageListEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/ImageSourceEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/ThumbnailEditor.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/AttendRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/ButtonRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/LinkRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx

토스트 알림 통일 적용

---

my-web-builder/apps/frontend/src/components/TemplateCanvasPreview.jsx
my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/hooks/useDeploy.js

Dashboard 템플릿 카드 비율, 미리보기 조정

---

backend/src/generator/generator.service.ts
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/DdayRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/DeployModal.jsx
my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx

디데이 컴포넌트 스케일 오류 해결, 주소 owner 재발행 오류 수정, 모달창 디자인 수정

디데이 컴포넌트 스케일 오류 해결, 주소 owner 재발행 오류 수정, 모달창 디자인 수정

---

my-web-builder/apps/subdomain-nextjs/components/renderers/ImageRenderer.jsx

이미지 배포화면 수정

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx

폰트 미리보기까지는 해결했고, 배포 페이지는 영준이가..
- close #523 
- 변경 1:
- 변경 2:

폰트 미리보기까지는 해결

---

my-web-builder/apps/subdomain-nextjs/components/renderers/ImageRenderer.jsx

2차 수정 이미지랜더러
- close # 
- 변경 1:
- 변경 2:

2차 수정 이미지랜더러

---

my-web-builder/apps/subdomain-nextjs/components/renderers/ImageRenderer.jsx

This reverts commit a260a3c38b9bd32b7813aba2addc77725421fdcd.
이전 커밋 취소합니다. 수정이 되서
- close # 
- 변경 1:
- 변경 2:

Revert "2차 수정 이미지랜더러"

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/LinkRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/WeddingInviteRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
my-web-builder/apps/subdomain-nextjs/components/renderers/CalendarRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/KakaoTalkShareRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/LinkRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/MapInfoRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/WeddingInviteRenderer.jsx
my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx

배포 후 화면 radius 불일치 오류 수정
카카오톡 공유, 링크, 안내장 컴포넌트 수정
컴포넌트 최소 높이 보장

배포 후 화면 radius 불일치 오류 수정/카카오톡 공유, 링크, 안내장 컴포넌트 수정/컴포넌트 최소 높이 보장

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/SlidoRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx
my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx

텍스트 컴포넌트 개선, 이미지와 그룹핑, 반응형 적용
@June0727-JUNGLE 아래 내용 확인하고 머지해주세요

텍스트 컴포넌트 개선, 이미지와 그룹핑, 반응형 적용

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/SlidoRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewModal.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx

컴포넌트 축소 문제 해결,  텍스트 세로기준 가운데 정렬, 미리보기 오류 해결,slido 컴포넌트 사이즈 오류 해결

컴포넌트 축소 문제 해결,  텍스트 세로기준 가운데 정렬, 미리보기 오류 해결,slido 컴포넌트 사이즈 오류 해결

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx

캔버스 가로 사이즈 에러 해결

---

backend/simple-server.js
backend/src/auth/auth.controller.ts
backend/src/auth/auth.module.ts
backend/src/auth/auth.service.ts
backend/src/auth/jwt.strategy.ts
backend/src/common/guards/jwt-auth.guard.ts
backend/src/main.ts
backend/src/templates/templates.service.ts
collaboration-performance-test.js
my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
my-web-builder/apps/frontend/src/hooks/useChat.js
my-web-builder/apps/frontend/src/hooks/useCollaboration.js
my-web-builder/apps/frontend/src/hooks/useLiveCursors.js
my-web-builder/apps/frontend/src/hooks/useYjsCollaboration.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
quick-collaboration-test.js
run-collaboration-test.sh

로그 일부 삭제, 줌 35%, 채팅 버그 수정

---

backend/src/users/users.controller.ts
backend/src/users/users.service.ts
my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx

채팅 줌인아웃 영향 x

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/GridGalleryRenderer.jsx

그리드 갤러리 편집모드에서 상호작용 막음

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/RectangleLayerEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/index.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/RectangleLayerThumbnail.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentLibrary/thumbnails/index.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/RectangleLayerRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/index.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor/Inspector.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PreviewRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/utils/editorUtils.js
my-web-builder/apps/frontend/src/pages/components/definitions/index.js
my-web-builder/apps/frontend/src/pages/components/definitions/rectangle-layer.json
my-web-builder/apps/subdomain-nextjs/components/renderers/RectangleLayerRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/index.js

사각형 컴포넌트 생성
- close # 
- 변경 1:
- 변경 2:

사각형 컴포넌트 추가

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx

지도 컴포넌트 주소 수정
- close #551 
- 변경 1:
- 변경 2:

지도 컴포넌트 주소 수정

---

my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
my-web-builder/apps/frontend/src/hooks/useLiveCursors.js

- 콘텐츠 좌표 기준의 통일된 좌표계와 CSS Transform 상쇄 기법을 통해 각 사용자의 줌 레벨과 관계없이 정확한 커서
- 캔버스 축소하면 커서랑 이름표 멀어지는 현상 제거

콘텐츠 좌표 기준의 통일된 좌표계와 CSS Transform 상쇄 기법을 통해 각 사용자의 줌 레벨과 관계없이 정확한 커서

---

my-web-builder/apps/frontend/src/App.tsx
my-web-builder/apps/frontend/src/components/collaboration/LiveCursors.jsx
my-web-builder/apps/frontend/src/hooks/useLiveCursors.js

- 캔버스 확대축소 시 커서 크기 동일
- 로그인 된 상태로 mainpage로 이동 시 dashboard로

캔버스 확대축소 시 커서 크기 동일, 로그인 된 상태로 mainpage로 이동 시 dashboard로

---

my-web-builder/apps/frontend/src/components/MasterStatusIndicator.jsx

마스터, 일반사용자 확인 섹션 비활성화

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/components/CanvasComponent.jsx
my-web-builder/apps/subdomain-nextjs/next-env.d.ts

사각형 컴포넌트 랜더링 고침

---

my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx

모바일 -> 모바일/데스크톱 오류 수정

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.module.ts
backend/src/auth/jwt.strategy.ts
backend/src/main.ts
my-web-builder/apps/frontend/src/App.tsx
my-web-builder/apps/frontend/src/config.js
my-web-builder/apps/frontend/src/hooks/useAutoSave.js
my-web-builder/apps/frontend/src/hooks/useLiveCursors.js
my-web-builder/apps/frontend/src/hooks/useMasterAutoSave.js
my-web-builder/apps/frontend/src/hooks/useMasterSystem.js
my-web-builder/apps/frontend/src/hooks/usePageDataManager.js
my-web-builder/apps/frontend/src/hooks/useYjsCollaboration.js
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapView.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/KakaoTalkShareRenderer.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentRenderers/TextRenderer.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/MapView.jsx
my-web-builder/apps/subdomain-nextjs/components/renderers/TextRenderer.jsx
my-web-builder/apps/subdomain-nextjs/pages/[pageId].tsx

로그아웃 시 메인 페이지로

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/MapEditor.jsx

지도 컴포넌트 에디터 수정

---

backend/src/auth/auth.service.ts
my-web-builder/apps/frontend/src/hooks/useComponentActions.js
my-web-builder/apps/frontend/src/hooks/useMasterSystem.js
my-web-builder/apps/frontend/src/pages/DashboardPage.jsx
my-web-builder/apps/frontend/src/pages/DeployedPage.jsx
my-web-builder/apps/frontend/src/pages/DraftsPage.jsx
my-web-builder/apps/frontend/src/pages/LoginPage.jsx
my-web-builder/apps/frontend/src/pages/MainPage.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/CanvasArea.jsx
my-web-builder/apps/subdomain-nextjs/next-env.d.ts

메인페이지에서 시작하기 누르면 로그인 페이지로 이동

---

my-web-builder/apps/frontend/src/pages/NoCodeEditor/ComponentEditors/CommentEditor.jsx
my-web-builder/apps/frontend/src/pages/NoCodeEditor/PropertyEditors/TextEditor.jsx

텍스트 에디터 및 댓글에디터 수정
